name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: ['5.6', '7.3']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: PHP syntax checker 7.3
      run: find . -type f -name '*.php' ! -path "./vendor/*" ! -path "./tests/*" -exec php -l -n {} \; | (! grep -v "No syntax errors detected")
    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - name: Run CS Fixer
      run: php vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --diff-format udiff